### ISSUE TITLE
Other Configuration items

### ISSUE THREAD

**Issue by BearBrew** [owntracks/quicksetup#51] opened 2024-07-23 20:11 UTC
Is there documentation for quicksetup's configuration.yaml to specify the following:
--> Connect to and use an already existing MQTT broker within the network
--> Specifying an alternative storage directory

**Comment by jpmens** [comment] 2024-07-24 05:47
No there isn't such documentation because Quicksetup was designed to be an all-in-one package and not rely on external components such as an existing MQTT broker.

Both the things you ask for are pretty straightforward though, and if you feel inclined towards working at a pull request for the code and documentation, we'd not say 'no' to it.

**Comment by jpmens** [comment] 2024-08-20 10:35
Closing with enhancement phrased in https://github.com/owntracks/quicksetup/issues/58

**Closed** 2024-08-20 10:37 UTC
Labels: enhancement, help wanted
